Repository propelorm/Propel2, pull requests merged in 2020-06, with the labels that each got.

#1530 add void return for application test
  tests/Propel/Tests/BookstoreLoggingTest.php
Labels: BC-break 2.0

#1556 Add phpstan on lowest level 1 for now.
  composer.json
  src/Propel/Generator/Behavior/AggregateColumn/AggregateColumnBehavior.php
  src/Propel/Generator/Manager/ReverseManager.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/Diff/TableComparator.php
  src/Propel/Generator/Model/PropelTypes.php
  src/Propel/Generator/Platform/OraclePlatform.php
  src/Propel/Runtime/ActiveQuery/Criterion/BasicCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/BinaryCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/InCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/LikeCriterion.php
  src/Propel/Runtime/Adapter/MSSQL/MssqlPropelPDO.php
  src/Propel/Runtime/Collection/Collection.php
  src/Propel/Runtime/Parser/XmlParser.php
  tests/phpstan.neon
Labels: BC-break 2.0

#1555 Use PSR-4 now.
  composer.json
Labels: Easy-pick

#1587 Fix SQLite sprintf() error
  src/Propel/Runtime/Adapter/Pdo/SqliteAdapter.php
Labels: Bug
