Repository propelorm/Propel2, pull requests merged in 2020-07, with the labels that each got.

#1598 fix(PDO): Can't prepare query with BINARY_ALL criteria when ATTR_EMUL…
  src/Propel/Runtime/ActiveQuery/Criterion/BinaryCriterion.php
  tests/Propel/Tests/Issues/Issue1192Test.php
Labels: Bug

#1588 Bugfix/phpstan level 1
  .travis.yml
  composer.json
  src/Propel/Common/Config/Exception/XmlParseException.php
  src/Propel/Generator/Behavior/ConcreteInheritance/ConcreteInheritanceBehavior.php
  src/Propel/Generator/Behavior/ConcreteInheritance/ConcreteInheritanceParentBehavior.php
  src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorQueryBuilderModifier.php
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Sql/Pgsql/PgsqlDataSQLBuilder.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Reverse/SqliteSchemaParser.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/Criterion/InModelCriterion.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  tests/phpstan.neon
Labels: Bug

#1590 Finish Symfony 5 support.
  src/Propel/Generator/Command/AbstractCommand.php
  src/Propel/Generator/Command/ConfigConvertCommand.php
  src/Propel/Generator/Command/DatabaseReverseCommand.php
  src/Propel/Generator/Command/GraphvizGenerateCommand.php
  src/Propel/Generator/Command/InitCommand.php
  src/Propel/Generator/Command/MigrationCreateCommand.php
  src/Propel/Generator/Command/MigrationDiffCommand.php
  src/Propel/Generator/Command/MigrationDownCommand.php
  src/Propel/Generator/Command/MigrationMigrateCommand.php
  src/Propel/Generator/Command/MigrationStatusCommand.php
  src/Propel/Generator/Command/MigrationUpCommand.php
  src/Propel/Generator/Command/ModelBuildCommand.php
  src/Propel/Generator/Command/SqlBuildCommand.php
  src/Propel/Generator/Command/SqlInsertCommand.php
  src/Propel/Generator/Command/TestPrepareCommand.php
Labels: Compatibility issue, Improvement

#1604 Add PHPStan level 1 check with baseline until we can remove symf2.
  .editorconfig
  .gitattributes
  .travis.yml
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorQueryBuilderModifier.php
Labels: Improvement

#1475 Allow option MYSQL_ATTR_SSL_VERIFY_SERVER_CERT to be set
  src/Propel/Common/Config/PropelConfiguration.php
Labels: Improvement

#1549 Fix issue where propel reverse breaks with system-versioned tables
  src/Propel/Generator/Reverse/MysqlSchemaParser.php
Labels: Bug

#1606 Remove nightly except one
  .travis.yml
Labels: Tests

#1612 Cleanup PHP versioning mentioned.
  composer.json
  resources/xsd/database.xsd
  src/Propel/Generator/Builder/Om/AbstractObjectBuilder.php
  src/Propel/Generator/Builder/Om/ExtensionObjectBuilder.php
  src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php
  src/Propel/Generator/Builder/Om/ExtensionQueryInheritanceBuilder.php
  src/Propel/Generator/Builder/Om/InterfaceBuilder.php
  src/Propel/Generator/Builder/Om/MultiExtendObjectBuilder.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/QueryInheritanceBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  tests/Propel/Tests/Helpers/Bookstore/BookstoreTestBase.php
  tests/Propel/Tests/Runtime/Map/GeneratedRelationMapTest.php
  tests/Propel/Tests/Runtime/Map/GeneratedRelationMapWithSchemasTest.php
Labels: Documentation

#1411 Update objectGetValidationFailures.php
  src/Propel/Generator/Behavior/Validate/templates/objectGetValidationFailures.php
Labels: Documentation

#1617 Fix return value for "no migration needed" case
  src/Propel/Generator/Command/MigrationMigrateCommand.php
Labels: Bug, Compatibility issue

#1621 Remove default value of optional parameters followed by required parameters
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
  tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaWithNamespaceTest.php
  tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaWithSchemaTest.php
Labels: Bug, Compatibility issue

#1623 Fix PHP8 warning.
  src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
Labels: Compatibility issue

#1607 Bugfix/phpstan lev3
  phpstan-baseline.neon
  phpstan.neon
  src/Propel/Common/Config/ConfigurationManager.php
  src/Propel/Common/Util/SetColumnConverter.php
  src/Propel/Generator/Builder/DataModelBuilder.php
  src/Propel/Generator/Builder/Om/AbstractObjectBuilder.php
  src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Config/GeneratorConfigInterface.php
  src/Propel/Generator/Model/BehaviorableTrait.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/ForeignKey.php
  src/Propel/Generator/Model/Index.php
  src/Propel/Generator/Model/Table.php
  src/Propel/Generator/Platform/DefaultPlatform.php
  src/Propel/Generator/Platform/MssqlPlatform.php
  src/Propel/Generator/Platform/MysqlPlatform.php
  src/Propel/Generator/Platform/OraclePlatform.php
  src/Propel/Generator/Platform/PgsqlPlatform.php
  src/Propel/Generator/Platform/PlatformInterface.php
  src/Propel/Generator/Platform/SqlitePlatform.php
  src/Propel/Generator/Reverse/AbstractSchemaParser.php
  src/Propel/Generator/Util/BehaviorLocator.php
  src/Propel/Generator/Util/PhpParser.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/Criterion/AbstractCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/AbstractModelCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/RawCriterion.php
  src/Propel/Runtime/ActiveQuery/Criterion/RawModelCriterion.php
  src/Propel/Runtime/Adapter/MSSQL/MssqlPropelPDO.php
  src/Propel/Runtime/Collection/OnDemandIterator.php
  src/Propel/Runtime/Connection/ConnectionInterface.php
  src/Propel/Runtime/Connection/ConnectionManagerPrimaryReplica.php
  src/Propel/Runtime/Connection/ConnectionManagerSingle.php
  src/Propel/Runtime/Connection/ConnectionWrapper.php
  src/Propel/Runtime/Connection/PdoConnection.php
  src/Propel/Runtime/Connection/StatementWrapper.php
  src/Propel/Runtime/DataFetcher/ArrayDataFetcher.php
  src/Propel/Runtime/DataFetcher/PDODataFetcher.php
  src/Propel/Runtime/Formatter/AbstractFormatter.php
  src/Propel/Runtime/Formatter/ArrayFormatter.php
  src/Propel/Runtime/Formatter/SimpleArrayFormatter.php
  src/Propel/Runtime/Map/RelationMap.php
  src/Propel/Runtime/Map/TableMap.php
  src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
  src/Propel/Runtime/Util/Profiler.php
  tests/Propel/Tests/Generator/Model/ColumnTest.php
  tests/Propel/Tests/Runtime/Util/ProfilerTest.php
Labels: Improvement

#1493 Do not try to fetch related objects of new object
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  tests/Propel/Tests/BookstoreTest.php
Labels: Bug

#1625 always create unique indices by constraint (for pgsql platform)
  src/Propel/Generator/Platform/PgsqlPlatform.php
  tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
  tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
  tests/Propel/Tests/Generator/Platform/OraclePlatformMigrationTest.php
  tests/Propel/Tests/Generator/Platform/PgsqlPlatformMigrationTest.php
  tests/Propel/Tests/Generator/Platform/PgsqlPlatformTest.php
  tests/Propel/Tests/Generator/Platform/PlatformMigrationTestProvider.php
  tests/Propel/Tests/Generator/Platform/PlatformTestProvider.php
Labels: Bug

#1628 Bugfix/phpstan level5
  phpstan-baseline.neon
  phpstan.neon
  src/Propel/Generator/Manager/ReverseManager.php
  tests/Propel/Tests/Generator/Command/DatabaseReverseTest.php
Labels: Compatibility issue, Improvement

#1631 add json to native pgsql type
  src/Propel/Generator/Reverse/PgsqlSchemaParser.php
Labels: Bug

#1633 Add missing badges
  README.md
Labels: Documentation
