Repository propelorm/Propel2, pull requests merged in 2021-01, with the labels that each got.

#1691 QuickBuilder refactor
  src/Propel/Generator/Util/QuickBuilder.php
  src/Propel/Generator/Util/VfsTrait.php
  tests/Propel/Tests/Common/Config/ConfigurationManagerTest.php
  tests/Propel/Tests/Common/Config/Loader/IniFileLoaderTest.php
  tests/Propel/Tests/Common/Config/Loader/JsonFileLoaderTest.php
  tests/Propel/Tests/Common/Config/Loader/PhpFileLoaderTest.php
  tests/Propel/Tests/Common/Config/Loader/XmlFileLoaderTest.php
  tests/Propel/Tests/Common/Config/Loader/YamlFileLoaderTest.php
  tests/Propel/Tests/Common/Config/XmlToArrayConverterTest.php
  tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php
  tests/Propel/Tests/Generator/Model/DatabaseTest.php
  tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
  tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
  tests/Propel/Tests/Generator/Util/QuickBuilderTest.php
  tests/Propel/Tests/Runtime/Parser/AbstractParserTest.php
Labels: Improvement

#1694 Updated TableMap generator to add column name map for normalization, …
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Runtime/Map/TableMap.php
Labels: Generator, Improvement

#1421 Fixes invalid hydration when using mergeWith of criteria with "with" models
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  tests/Propel/Tests/Issues/Issue1420Test.php
  tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
Labels: Bug

#1698 Avoid "Undefined index: column" in Criteria.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
Labels: Bug
