Repository propelorm/Propel2, pull requests merged in 2021-05, with the labels that each got.

#1727 Show failed queries and SQL error in debug mode exception
  phpstan-baseline.neon
  src/Propel/Runtime/ActiveQuery/Criteria.php
  tests/Propel/Tests/Runtime/Util/TableMapExceptionsTest.php
Labels: Bug, Improvement

#1726 fixes duplicate keys in normalizedColumnNameMap
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
Labels: Bug

#1729 fix doubly namespaces during database:reverse / write absolute namespaces to schema.xml
  phpstan-baseline.neon
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Manager/ReverseManager.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/ScopedMappingModel.php
  src/Propel/Generator/Model/Table.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  tests/Propel/Tests/Generator/Builder/Om/AbstractOMBuilderNamespaceTest.php
  tests/Propel/Tests/Generator/Model/DatabaseTest.php
  tests/Propel/Tests/Generator/Model/TableTest.php
  tests/Propel/Tests/Resources/blog-database.php
  tests/Propel/Tests/Resources/blog-database.xml
  tests/Propel/Tests/Resources/blog-schema.xml
Labels: Bug

#1737 Feature/generate data dictionary documentation
  src/Propel/Common/Config/ConfigurationManager.php
  src/Propel/Generator/Command/DataDictionaryExportCommand.php
  src/Propel/Generator/Manager/DataDictionaryExportManager.php
  tests/Propel/Tests/Generator/Command/DataDictionaryExportCommandTest.php
Labels: Feature

#1734 Bugfix: Escape quotes in behavior
  src/Propel/Generator/Behavior/AggregateMultipleColumns/templates/objectCompute.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Builder/Om/templates/tableMapClearRelatedInstancePool.php
  tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
Labels: Bug

#1732 Bugfixes for abstract tables
  src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Model/Table.php
  tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
  tests/Propel/Tests/Generator/Builder/Om/TestableQueryBuilder.php
Labels: Bug, Improvement
