Repository propelorm/Propel2, pull requests merged in 2021-12, with the labels that each got.

#1798 phpdoc: one-to-one reference getter can return null
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
Labels: Documentation

#1809 Remove deprecated ATOM datetime format.
  src/Propel/Runtime/Parser/XmlParser.php
  tests/Propel/Tests/Runtime/Parser/XmlParserTest.php
Labels: Compatibility issue

#1797 Format insert TIME values as H:i:s.u instead of 'Y-m-d H:i:s.u'
  src/Propel/Generator/Platform/DefaultPlatform.php
Labels: Tests Needed

#1806 Fix up typos.
  phpstan-baseline.neon
  src/Propel/Common/Config/Loader/FileLoader.php
  src/Propel/Common/Config/PropelConfiguration.php
  src/Propel/Generator/Behavior/AggregateMultipleColumns/AggregateMultipleColumnsBehavior.php
  src/Propel/Generator/Behavior/Archivable/templates/queryArchive.php
  src/Propel/Generator/Behavior/ConcreteInheritance/ConcreteInheritanceParentBehavior.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Command/AbstractCommand.php
  src/Propel/Generator/Manager/AbstractManager.php
  src/Propel/Generator/Model/Behavior.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/Diff/TableDiff.php
  src/Propel/Generator/Model/ForeignKey.php
  src/Propel/Generator/Model/Index.php
  src/Propel/Generator/Model/PropelTypes.php
  src/Propel/Generator/Model/Schema.php
  src/Propel/Generator/Model/ScopedMappingModel.php
  src/Propel/Generator/Model/Table.php
  src/Propel/Generator/Model/Unique.php
  src/Propel/Generator/Model/VendorInfo.php
  src/Propel/Generator/Platform/DefaultPlatform.php
  src/Propel/Generator/Platform/SqlitePlatform.php
  src/Propel/Generator/Schema/Dumper/DumperInterface.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/DeleteQuerySqlBuilder.php
  src/Propel/Runtime/Collection/Collection.php
  src/Propel/Runtime/Connection/ConnectionWrapper.php
  src/Propel/Runtime/Connection/ProfilerConnectionWrapper.php
  src/Propel/Runtime/DataFetcher/AbstractDataFetcher.php
  src/Propel/Runtime/Map/TableMap.php
  src/Propel/Runtime/Util/Profiler.php
  tests/Propel/Tests/Common/Config/DataProviderTrait.php
  tests/Propel/Tests/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifierTest.php
  tests/Propel/Tests/Generator/Config/ArrayToPhpConverterTest.php
  tests/Propel/Tests/Generator/Model/ModelTestCase.php
  tests/Propel/Tests/Runtime/ServiceContainer/StandardServiceContainerTest.php
  tests/Propel/Tests/Runtime/Util/ProfilerTest.php
Labels: BC-break 2.0, Compatibility issue

#1813 Add tests for $stmt->bindValue()
  tests/Propel/Tests/Generator/Platform/DefaultPlatformTest.php
Labels: Tests

#1805 PHP ^7.4 Compatibility (Including 8.1)
  .github/workflows/ci.yml
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/Propel/Common/Config/Loader/IniFileLoader.php
  src/Propel/Common/Config/XmlToArrayConverter.php
  src/Propel/Generator/Builder/DataModelBuilder.php
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Om/ClassTools.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/QueryInheritanceBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Builder/Util/PropelTemplate.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Config/GeneratorConfig.php
  src/Propel/Generator/Manager/MigrationManager.php
  src/Propel/Generator/Manager/ReverseManager.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/Diff/ColumnComparator.php
  src/Propel/Generator/Model/Diff/ForeignKeyComparator.php
  src/Propel/Generator/Model/Domain.php
  src/Propel/Generator/Model/MappingModel.php
  src/Propel/Generator/Model/PhpNameGenerator.php
  src/Propel/Generator/Model/PropelTypes.php
  src/Propel/Generator/Model/ScopedMappingModel.php
  src/Propel/Generator/Platform/SqlitePlatform.php
  src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
  src/Propel/Runtime/ActiveRecord/NestedSetRecursiveIterator.php
  src/Propel/Runtime/Collection/Collection.php
  src/Propel/Runtime/Collection/CollectionIterator.php
  src/Propel/Runtime/Collection/ObjectCollection.php
  src/Propel/Runtime/Collection/OnDemandCollection.php
  src/Propel/Runtime/Collection/OnDemandIterator.php
  src/Propel/Runtime/DataFetcher/ArrayDataFetcher.php
  src/Propel/Runtime/DataFetcher/DataFetcherInterface.php
  src/Propel/Runtime/DataFetcher/PDODataFetcher.php
  src/Propel/Runtime/Map/DatabaseMap.php
  src/Propel/Runtime/Map/TableMap.php
  src/Propel/Runtime/Parser/CsvParser.php
  src/Propel/Runtime/Util/PropelDateTime.php
  src/Propel/Runtime/Util/PropelModelPager.php
  tests/Propel/Tests/Generator/Behavior/Validate/UniqueConstraintTest.php
  tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php
  tests/Propel/Tests/Generator/Model/MappingModelTest.php
Labels: Compatibility issue

#1814 Added `isSelfSelected` property to the `clear` method
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  tests/Propel/Tests/Runtime/ActiveQuery/PropelQueryTest.php
Labels: Bug
