Repository propelorm/Propel2, pull requests merged in 2021-08, with the labels that each got.

#1772 [#1284] pluralise 'Box' to 'Boxes'
  src/Propel/Common/Pluralizer/StandardEnglishPluralizer.php
  tests/Propel/Tests/Common/Pluralizer/EnglishPluralizerTest.php
Labels: BC-break 2.0, Bug

#1773 Allow NO ACTION for foreign key references (in the dtd/xsd)
  resources/dtd/database.dtd
  resources/xsd/database.xsd
  src/Propel/Generator/Model/ForeignKey.php
  tests/Propel/Tests/Generator/Model/ForeignKeyTest.php
Labels: Improvement

#1775 BC break: rename functions with underscores for PSR2 compat
  config/phpcs.xml
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
Labels: BC-break 2.0

#1776 Use object-equality instead of reference-equality to compare object properties
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  tests/Propel/Tests/Common/BoxedString.php
  tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTest.php
Labels: Improvement

#1747 Feature/untangle criteria class
  phpstan-baseline.neon
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/Criterion/AbstractCriterion.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/AbstractQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/CountQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/DeleteAllQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/DeleteQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/InsertQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/QueryExecutionException.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/SelectQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/UpdateQueryExecutor.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/AbstractSqlQueryBuilder.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/CountQuerySqlBuilder.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/DeleteQuerySqlBuilder.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/InsertQuerySqlBuilder.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/PreparedStatementDto.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/SelectQuerySqlBuilder.php
  src/Propel/Runtime/ActiveQuery/SqlBuilder/UpdateQuerySqlBuilder.php
  src/Propel/Runtime/Adapter/AdapterInterface.php
  src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
  src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php
  src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php
  src/Propel/Runtime/Adapter/Pdo/PgsqlAdapter.php
  src/Propel/Runtime/Adapter/Pdo/SqliteAdapter.php
  src/Propel/Runtime/Adapter/Pdo/SqlsrvAdapter.php
  src/Propel/Runtime/Adapter/SqlAdapterInterface.php
  tests/Propel/Tests/Runtime/ActiveQuery/QueryExecutor/AbstractQueryExecutorTest.php
  tests/Propel/Tests/Runtime/ActiveQuery/QueryExecutor/SelectQueryExecutorTest.php
  tests/Propel/Tests/Runtime/ActiveQuery/SqlBuilder/SelectQuerySqlBuilderTest.php
  tests/Propel/Tests/Runtime/Util/TableMapExceptionsTest.php
Labels: Improvement
