Repository propelorm/Propel2, pull requests merged in 2022-03, with the labels that each got.

#1846 Cleanup on deprecated API
  src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
  src/Propel/Generator/Manager/AbstractManager.php
  src/Propel/Generator/Model/Table.php
Labels: BC-break 2.0, Compatibility issue, Improvement

#1850 Fix up phpstan silencing.
  phpstan-baseline.neon
  src/Propel/Runtime/Formatter/AbstractFormatter.php
Labels: Documentation, Bug

#1851 Fix up phpstan baseline.
  phpstan-baseline.neon
  src/Propel/Generator/Builder/DataModelBuilder.php
  src/Propel/Generator/Config/GeneratorConfig.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/ForeignKey.php
  src/Propel/Generator/Platform/MysqlPlatform.php
  src/Propel/Generator/Platform/PgsqlPlatform.php
  src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
Labels: Improvement

#1853 Fix up phpstan silencing.
  phpstan-baseline.neon
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  src/Propel/Runtime/Validator/Constraints/UniqueValidator.php
Labels: Compatibility issue

#1855 Add BC shim for template lookup in former directories.
  src/Propel/Common/Util/PathTrait.php
Labels: BC-break 2.0, Compatibility issue, Improvement

#1849 Bugfix/strict param types master merged
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Manager/MigrationManager.php
  src/Propel/Generator/Model/Behavior.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/ScopedMappingModel.php
  src/Propel/Generator/Model/Table.php
  src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
  src/Propel/Runtime/ActiveQuery/Join.php
  src/Propel/Runtime/ActiveRecord/ActiveRecordInterface.php
  src/Propel/Runtime/Formatter/AbstractFormatterWithHydration.php
  src/Propel/Runtime/Formatter/ArrayFormatter.php
  src/Propel/Runtime/Map/ColumnMap.php
  src/Propel/Runtime/Map/RelationMap.php
  src/Propel/Runtime/Map/TableMap.php
  src/Propel/Runtime/Util/PropelModelPager.php
  tests/Propel/Tests/FieldnameRelatedTest.php
  tests/Propel/Tests/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifierTest.php
  tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectWithFixturesTest.php
  tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php
  tests/Propel/Tests/Generator/Config/QuickGeneratorConfigTest.php
  tests/Propel/Tests/Generator/Model/BehaviorTest.php
  tests/Propel/Tests/Generator/Model/ColumnTest.php
  tests/Propel/Tests/Generator/Model/DatabaseTest.php
  tests/Propel/Tests/Generator/Model/Diff/ColumnComparatorTest.php
  tests/Propel/Tests/Generator/Model/Diff/PropelTableColumnComparatorTest.php
  tests/Propel/Tests/Generator/Model/Diff/PropelTableIndexComparatorTest.php
  tests/Propel/Tests/Generator/Model/Diff/PropelTablePkColumnComparatorTest.php
  tests/Propel/Tests/Generator/Model/Diff/TableDiffTest.php
  tests/Propel/Tests/Generator/Model/TableTest.php
  tests/Propel/Tests/Generator/Platform/DefaultPlatformTest.php
  tests/Propel/Tests/Generator/Platform/PlatformMigrationTestProvider.php
  tests/Propel/Tests/Runtime/ActiveRecordConvertTest.php
  tests/Propel/Tests/Runtime/Collection/ArrayCollectionTest.php
  tests/Propel/Tests/Runtime/Collection/ObjectCollectionTest.php
  tests/Propel/Tests/Runtime/Map/ColumnMapTest.php
  tests/Propel/Tests/Runtime/Map/RelationMapTest.php
  tests/Propel/Tests/Runtime/Map/TableMapTest.php
Labels: BC-break 2.0, Compatibility issue, Improvement, Prio
