Repository propelorm/Propel2, pull requests merged in 2022-08, with the labels that each got.

#1897 Run tests with latest monolog
  composer.json
  phpcs.xml
Labels: Tests

#1902 load table maps lazily
  psalm-baseline.xml
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Runtime/Map/DatabaseMap.php
  src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
  templates/Builder/Om/tableMapConstants.php
  tests/Propel/Tests/Runtime/Map/DatabaseMapTest.php
Labels: Improvement

#1904 Fix invalid duplicate indices using ArchivableBehavior for some platforms
  src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
  tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
Labels: Bug

#1903 Fix duplicate indices when converting unique index to index
  src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
  tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
Labels: Bug
