Repository propelorm/Propel2, pull requests merged in 2022-01, with the labels that each got.

#1818 Remove Symfony <4.4 support
  composer.json
  psalm-baseline.xml
  src/Propel/Common/Config/PropelConfiguration.php
  src/Propel/Generator/Command/Console/Input/ArrayInput.php
  src/Propel/Generator/Command/Helper/ConsoleHelper.php
  src/Propel/Generator/Command/Helper/ConsoleHelper3.php
  src/Propel/Generator/Command/Helper/ConsoleHelperInterface.php
  src/Propel/Generator/Command/InitCommand.php
  tests/composer/composer-symfony3-max.json
  tests/composer/composer-symfony3-min.json
  tests/composer/composer-symfony4-max.json
  tests/composer/composer-symfony4-min.json
Labels: BC-break 2.0, Compatibility issue, Improvement

#1822 Allow Monolog v2 to enable psr/log v2/v3
  composer.json
  src/Propel/Runtime/Connection/ConnectionWrapper.php
Labels: Compatibility issue, Improvement

#1823 Use explode() instead of preg_split().
  .github/workflows/ci.yml
  src/Propel/Generator/Command/AbstractCommand.php
  src/Propel/Generator/Reverse/MysqlSchemaParser.php
  src/Propel/Runtime/Parser/CsvParser.php
Labels: Improvement
