Repository propelorm/Propel2, pull requests merged in 2022-04, with the labels that each got.

#1862 Cleanup API and docblocks
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
  src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
  src/Propel/Generator/Behavior/Sortable/SortableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/Sortable/SortableBehaviorQueryBuilderModifier.php
  src/Propel/Generator/Behavior/Timestampable/TimestampableBehavior.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/ConstraintNameGenerator.php
  src/Propel/Generator/Model/Domain.php
  src/Propel/Generator/Util/SqlParser.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  src/Propel/Runtime/Connection/ConnectionWrapper.php
  src/Propel/Runtime/Formatter/AbstractFormatter.php
  src/Propel/Runtime/Map/ColumnMap.php
  src/Propel/Runtime/Map/DatabaseMap.php
  src/Propel/Runtime/Parser/AbstractParser.php
  src/Propel/Runtime/Parser/CsvParser.php
  src/Propel/Runtime/Parser/JsonParser.php
Labels: Bug, BC-break 2.0, Compatibility issue

#1865 [WIP] Added strict types in generated code
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  templates/Builder/Om/tableMapFields.php
  templates/Builder/Om/tableMapInstancePool.php
Labels: BC-break 2.0, Compatibility issue, Improvement

#1876 Adjust return type of Query::find methods
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  tests/Propel/Tests/Runtime/ActiveQuery/PropelQueryTest.php
Labels: Bug, Compatibility issue

#1872 add type-safe access to StandardServiceContainer
  src/Propel/Runtime/Propel.php
  tests/Propel/Tests/Runtime/PropelTest.php
Labels: Improvement
