Repository propelorm/Propel2, pull requests merged in 2023-01, with the labels that each got.

#1938 Fix PHPStan
  src/Propel/Common/Config/Loader/FileLoader.php
  src/Propel/Runtime/Util/PropelDateTime.php
  src/Propel/Runtime/Util/UuidConverter.php
  src/Propel/Runtime/Validator/Constraints/UniqueValidator.php
  tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
Labels: Compatibility issue

#1932 Implemented migration rollback.
  src/Propel/Generator/Command/Executor/RollbackExecutor.php
  src/Propel/Generator/Command/MigrationDownCommand.php
  src/Propel/Generator/Command/MigrationMigrateCommand.php
  src/Propel/Generator/Command/MigrationStatusCommand.php
  src/Propel/Generator/Manager/MigrationManager.php
  tests/Fixtures/migrate-to-version/version-1/schema.xml
  tests/Fixtures/migrate-to-version/version-2/schema.xml
  tests/Fixtures/migrate-to-version/version-3/schema.xml
  tests/Propel/Tests/Generator/Command/MigrationTest.php
  tests/Propel/Tests/Generator/Manager/MigrationManagerTest.php
Labels: Feature

#1940 Fix CS for array in PHP generated files.
  src/Propel/Common/Config/Loader/PhpFileLoader.php
  src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  templates/Manager/migration_template.php
  tests/Propel/Tests/Common/Config/Loader/PhpFileLoaderTest.php
  tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php
Labels: Improvement

#1945 Fix CS by removing inline assignment.
  src/Propel/Generator/Behavior/I18n/I18nBehavior.php
  src/Propel/Generator/Behavior/I18n/I18nBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehavior.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Om/QueryInheritanceBuilder.php
  src/Propel/Generator/Builder/Om/TableMapBuilder.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Config/GeneratorConfig.php
  src/Propel/Generator/Model/Database.php
  src/Propel/Generator/Model/Diff/ColumnComparator.php
  src/Propel/Generator/Model/Domain.php
  src/Propel/Generator/Model/ForeignKey.php
  src/Propel/Generator/Model/Schema.php
  src/Propel/Generator/Platform/MysqlPlatform.php
  src/Propel/Generator/Platform/PgsqlPlatform.php
  src/Propel/Generator/Platform/SqlitePlatform.php
  src/Propel/Generator/Reverse/MssqlSchemaParser.php
  src/Propel/Generator/Reverse/MysqlSchemaParser.php
  src/Propel/Generator/Reverse/OracleSchemaParser.php
  src/Propel/Generator/Reverse/PgsqlSchemaParser.php
  src/Propel/Generator/Reverse/SqliteSchemaParser.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  src/Propel/Generator/Util/PhpParser.php
  src/Propel/Generator/Util/QuickBuilder.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  src/Propel/Runtime/Collection/ObjectCollection.php
  src/Propel/Runtime/Map/ColumnMap.php
  src/Propel/Runtime/Map/DatabaseMap.php
Labels: Improvement

#1948 Fix up PHPStan errors.
  src/Propel/Generator/Builder/Util/PropelTemplate.php
  src/Propel/Generator/Reverse/PgsqlSchemaParser.php
  src/Propel/Generator/Reverse/SqliteSchemaParser.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
  src/Propel/Runtime/Adapter/Pdo/OracleAdapter.php
Labels: Improvement

#1947 Fix up datetime PHPStan error.
  src/Propel/Common/Config/XmlToArrayConverter.php
  src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
  src/Propel/Generator/Behavior/Sortable/SortableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/Sortable/SortableBehaviorQueryBuilderModifier.php
  src/Propel/Generator/Builder/Om/TableMapLoaderScriptBuilder.php
  src/Propel/Runtime/DataFetcher/AbstractDataFetcher.php
  src/Propel/Runtime/Util/PropelDateTime.php
Labels: Improvement

#1950 Fix up IDE found errors/problems.
  src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
  src/Propel/Generator/Behavior/Timestampable/TimestampableBehavior.php
  src/Propel/Generator/Behavior/Validate/ValidateBehavior.php
  src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
  src/Propel/Generator/Builder/DataModelBuilder.php
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Om/ObjectBuilder.php
  src/Propel/Generator/Builder/Om/QueryBuilder.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Command/TestPrepareCommand.php
  src/Propel/Generator/Config/ArrayToPhpConverter.php
  src/Propel/Generator/Model/Behavior.php
  src/Propel/Generator/Model/BehaviorableTrait.php
  src/Propel/Generator/Model/Diff/TableDiff.php
  src/Propel/Generator/Model/Domain.php
  src/Propel/Generator/Model/PhpNameGenerator.php
  src/Propel/Generator/Model/Table.php
  src/Propel/Generator/Platform/DefaultPlatform.php
  src/Propel/Generator/Platform/PgsqlPlatform.php
  src/Propel/Generator/Platform/PlatformInterface.php
  src/Propel/Generator/Reverse/AbstractSchemaParser.php
  src/Propel/Generator/Reverse/MysqlSchemaParser.php
  src/Propel/Generator/Reverse/PgsqlSchemaParser.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  src/Propel/Generator/Util/QuickBuilder.php
  src/Propel/Runtime/ActiveQuery/Criterion/AbstractCriterion.php
  src/Propel/Runtime/ActiveQuery/Join.php
  src/Propel/Runtime/ActiveQuery/ModelCriteria.php
  src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php
  src/Propel/Runtime/Collection/Collection.php
  src/Propel/Runtime/Collection/CollectionIterator.php
  src/Propel/Runtime/Connection/ConnectionWrapper.php
  src/Propel/Runtime/Formatter/AbstractFormatterWithHydration.php
  src/Propel/Runtime/Formatter/OnDemandFormatter.php
  src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
  src/Propel/Runtime/Util/PropelConditionalProxy.php
  src/Propel/Runtime/Util/PropelDateTime.php
Labels: Improvement

#1951 Fixes phpstan errors, set PHPStan to level 7
  composer.json
  phpstan.neon
  src/Propel/Common/Config/XmlToArrayConverter.php
  src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
  src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
  src/Propel/Generator/Builder/Util/SchemaReader.php
  src/Propel/Generator/Command/AbstractCommand.php
  src/Propel/Generator/Command/ConfigConvertCommand.php
  src/Propel/Generator/Command/InitCommand.php
  src/Propel/Generator/Command/TestPrepareCommand.php
  src/Propel/Generator/Manager/AbstractManager.php
  src/Propel/Generator/Manager/MigrationManager.php
  src/Propel/Generator/Manager/ModelManager.php
  src/Propel/Generator/Manager/SqlManager.php
  src/Propel/Generator/Model/Behavior.php
  src/Propel/Generator/Model/Column.php
  src/Propel/Generator/Model/ColumnDefaultValue.php
  src/Propel/Generator/Model/Diff/ColumnComparator.php
  src/Propel/Generator/Model/Domain.php
  src/Propel/Generator/Model/NameFactory.php
  src/Propel/Generator/Platform/DefaultPlatform.php
  src/Propel/Generator/Platform/OraclePlatform.php
  src/Propel/Generator/Platform/PgsqlPlatform.php
  src/Propel/Generator/Platform/SqlitePlatform.php
  src/Propel/Generator/Reverse/MssqlSchemaParser.php
  src/Propel/Generator/Reverse/MysqlSchemaParser.php
  src/Propel/Generator/Reverse/OracleSchemaParser.php
  src/Propel/Generator/Reverse/PgsqlSchemaParser.php
  src/Propel/Generator/Schema/Dumper/XmlDumper.php
  src/Propel/Generator/Util/BehaviorLocator.php
  src/Propel/Generator/Util/QuickBuilder.php
  src/Propel/Generator/Util/VfsTrait.php
  src/Propel/Runtime/ActiveQuery/Criteria.php
  src/Propel/Runtime/ActiveQuery/Join.php
  src/Propel/Runtime/ActiveQuery/QueryExecutor/AbstractQueryExecutor.php
  src/Propel/Runtime/Adapter/Pdo/PgsqlAdapter.php
  src/Propel/Runtime/Collection/CollectionIterator.php
  src/Propel/Runtime/Collection/ObjectCollection.php
  src/Propel/Runtime/Collection/OnDemandIterator.php
  src/Propel/Runtime/Connection/PdoConnection.php
  src/Propel/Runtime/Connection/StatementInterface.php
  src/Propel/Runtime/Connection/StatementWrapper.php
  src/Propel/Runtime/Formatter/AbstractFormatterWithHydration.php
  src/Propel/Runtime/Formatter/OnDemandFormatter.php
  src/Propel/Runtime/Map/DatabaseMap.php
  src/Propel/Runtime/Util/PropelConditionalProxy.php
Labels: Improvement
